version: '3.8'

services:
  celestia-app1:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'app1'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090
    volumes:
      - ./da-network/node1:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.2

  celestia-app2:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'app2'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 36656:26656
      - 36657:26657
      - 11317:1317
      - 19090:9090
    volumes:
      - ./da-network/node2:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.3

  celestia-app3:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'app3'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 46656:26656
      - 46657:26657
      - 21317:1317
      - 29090:9090
    volumes:
      - ./da-network/node3:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.4


  celestia-app4:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'app4'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 56656:26656
      - 56657:26657
      - 31317:1317
      - 39090:9090
    volumes:
      - ./da-network/node4:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.5


  celestia-bridge-node:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'bridge-node'
    environment:
      NODE_STORE: '/home/celestia/bridge/'
      NODE_TYPE: 'bridge'
    command: 'sh -c /home/celestia/celestia-bridge-start.sh'
    ports:
      - 26650:26650
      - 26658:26658
      - 26659:26659
      - 2121:2121
      - 8080:8080
    volumes:
      - ./da-network/bridge:/home/celestia/bridge
      - ./da-network/shell/celestia-bridge-start.sh:/home/celestia/celestia-bridge-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.6

  celestia-full-node:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'full-node'
    environment:
      NODE_STORE: '/home/celestia/full/'
      NODE_TYPE: 'full'
    command: 'sh -c /home/celestia/celestia-full-start.sh'
    ports:
      - 36650:26650
      - 36658:26658
      - 36659:26659
      - 3121:2121
    volumes:
      - ./da-network/full:/home/celestia/full
      - ./da-network/shell/celestia-full-start.sh:/home/celestia/celestia-full-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.7

  celestia-light-node1:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'light-node1'
    environment:
      NODE_STORE: '/home/celestia/light1/'
      NODE_TYPE: 'light'
    command: 'sh -c /home/celestia/celestia-light1-start.sh'
    ports:
      - 46650:26650
      - 46658:26658
      - 46659:26659
      - 4121:2121
    volumes:
      - ./da-network/light1:/home/celestia/light
      - ./da-network/shell/celestia-light1-start.sh:/home/celestia/celestia-light1-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.8

  celestia-light-node2:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'light-node2'
    environment:
      NODE_STORE: '/home/celestia/light2/'
      NODE_TYPE: 'light'
    command: 'sh -c /home/celestia/celestia-light2-start.sh'
    ports:
      - 56650:26650
      - 56658:26658
      - 56659:26659
      - 5121:2121
    volumes:
      - ./da-network/light2:/home/celestia/light
      - ./da-network/shell/celestia-light2-start.sh:/home/celestia/celestia-light2-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.9


  celestia-bridge-node2:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'bridge-node2'
    environment:
      NODE_STORE: '/home/celestia/bridge/'
      NODE_TYPE: 'bridge'
    command: 'sh -c /home/celestia/celestia-bridge-start.sh'
    ports:
      - 27650:26650
      - 27658:26658
      - 27659:26659
      - 2721:2121
      - 8780:8080
    volumes:
      - ./da-network/bridge2:/home/celestia/bridge
      - ./da-network/shell/celestia-bridge2-start.sh:/home/celestia/celestia-bridge-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.10


  celestia-full-node2:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'full-node2'
    environment:
      NODE_STORE: '/home/celestia/full/'
      NODE_TYPE: 'full'
    command: 'sh -c /home/celestia/celestia-full-start.sh'
    ports:
      - 28650:26650
      - 28658:26658
      - 28659:26659
      - 2821:2121
      - 8880:8080
    volumes:
      - ./da-network/full2:/home/celestia/full
      - ./da-network/shell/celestia-full2-start.sh:/home/celestia/celestia-full-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.11


  celestia-full-node3:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'full-node3'
    environment:
      NODE_STORE: '/home/celestia/full/'
      NODE_TYPE: 'full'
    command: 'sh -c /home/celestia/celestia-full-start.sh'
    ports:
      - 29650:26650
      - 29658:26658
      - 29659:26659
      - 2921:2121
    volumes:
      - ./da-network/full3:/home/celestia/full
      - ./da-network/shell/celestia-full3-start.sh:/home/celestia/celestia-full-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.12

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.0.0/16