version: '3.8'

services:
  app:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'celestia-app'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090
    volumes:
      - ./celestia/.celestia-app:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.2

  bridge-node:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'celestia-bridge-node'
    environment:
      NODE_STORE: '/home/celestia/bridge/'
      NODE_TYPE: 'bridge'
    command: 'sh -c /home/celestia/celestia-da-start.sh'
    ports:
      - 26650:26650
      - 26658:26658
      - 26659:26659
    volumes:
      - ./celestia/bridge:/home/celestia/bridge
      - ./celestia-da-start.sh:/home/celestia/celestia-da-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.0.0/16