version: '3.8'

services:
  celestia-app:
    image: ernest/celestia-app:v1.6.0
    restart: always
    container_name: 'app'
    command: 'start --grpc.enable &'
    environment:
      APP_PATH: '/home/celestia/'
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090
    volumes:
      - ./celestia/.celestia-app:/home/celestia/.celestia-app
    networks:
      localnet:
        ipv4_address: 192.167.0.2

  celestia-bridge-node:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'bridge-node'
    environment:
      NODE_STORE: '/home/celestia/bridge/'
      NODE_TYPE: 'bridge'
    command: 'sh -c /home/celestia/celestia-bridge-start.sh'
    ports:
      - 26650:26650
      - 26658:26658
      - 26659:26659
      - 2121:2121
    volumes:
      - ./celestia/bridge:/home/celestia/bridge
      - ./celestia-bridge-start.sh:/home/celestia/celestia-bridge-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.3


  celestia-full-node:
    image: ernest/celestia-da:v0.12.9
    restart: always
    container_name: 'full-node'
    environment:
      NODE_STORE: '/home/celestia/full/'
      NODE_TYPE: 'full'
    command: 'sh -c /home/celestia/celestia-full-start.sh'
    ports:
      - 36650:26650
      - 36658:26658
      - 36659:26659
      - 3121:2121
    volumes:
      - ./celestia/full:/home/celestia/full
      - ./celestia-full-start.sh:/home/celestia/celestia-full-start.sh
    networks:
      localnet:
        ipv4_address: 192.167.0.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.0.0/16